:global:
  build:
    matrix:
      - GOOS: linux
        GOARCH: amd64
      - GOOS: darwin
        GOARCH: amd64
.travis.yml:
  env:
    global:
      - ORG_PATH=/home/travis/gopath/src/github.com/intelsdi-x
      - SNAP_PLUGIN_SOURCE=/home/travis/gopath/src/github.com/${TRAVIS_REPO_SLUG}
    matrix:
      - TEST_TYPE=small
      - TEST_TYPE=medium
  deploy:
    access_key_id: AKIAINMB43VSSPFZISAA
    secret_access_key:
      secure: NSjryYJMqALgAGAnyvusH+eiiPS37DR2BGfVzsieOVv6mDGf6aSe59zKkxcfvEOdypt3TgRuhxsPyS+/7mOEUDcBh6VtyR+CIXtfVcJ/ns6CGDkgyyRt1tcU/1BtTzS2gcNNN5zMkG5GGHdZT3ZtBbEWXepuEleD423dttL5zEA90QF+pgvoWrI1hprnBCBUAVeb6DGiv2/NbTOrwh4NapBMgkOzD9hpMXD9MXKZnELnOhajGqeI8fCpMoo+qnktiUsSevVp3siSUzJvobGUXJsUpIZRa5A5kQ8vbsrXvTWSecvsWRFmgWLi9Yr9FhGS5VIrvoSQe4p2EZY3+OtGMcfuJ0tEQe3tU6gq1Unz7tE+aKScl3Cck9Ds2PfZk0AQjM4RrgLAexG+EAmLidH+NftQCE6+y8ha0usmD9iuNj/NZaakP459/OjxslYKXaf8zOenH3JLtMCbtX3YBZi3b24AqXha0T0gFGzYjni6ek4hSw6YO/18dLhZMomoVqo+RFbx+HBQ+cBNgLUiWKYGcZOQAikBt2AxeT/VfVYkMlULQuKjgLNUIbQ7egKRUeBfT0zx/1yP2w6gGCJRrz27y/NzVK3pI8AqDNw+CtpVpIseGjH4PBt7CXwM/yqnhw15kWQLM2NIplGgf+Kyq2jyQkgiBNI7iQPwfDZ7EvNRIbY=
    api_key:
      secure: BEm3q1po7Dt5MHKek73U2SjKTxgYH8OG5YDd3q7IvqABuoZtpG1fU45121H9mdW81Uw6o7KySPy/eyywGsc6WKwmZcGvX4bo/AeXkDFDwwPvKCbDaf2MspqlepvQaUPAk3qEYaQ35WrhCUBw1yMb4wjfldjpcg2EdYz0AJNgJhiBk7OBrJsIAk5Rhlufk7W4gwGEPsnkohp8fCjVpurd8oX1cmNSnLJSQHacT37Rf3SwJNZNtIkACfFzI8XILVMrxu6fDBhQi4LvnZzaC4LvPcQuYvH61Cu5gy63s5kiWmaYxAISA1Qs2aUtp/tTz6Y6IAcUix8RSRCv1KQ9H0kO78NN1o3N8SxbiM3KfXjM+pomUvdECNQhWtaTohm7nJCD3e9budN8e0VQewcu744Hv0fGUwPVnWcrRdSvlvju5xgqps1iwQ4cDaQRi9zfeqOsfwocTK5oUDQolGhJvHogA14upnfo11PjTK1d4YCdCPAUbPLGJx9MGLuzaNfVscVQSL9+SdOH5RM6TTbta+uchpTUe9DgxkyMRoe5Wm2O4T+ag9r8+GjbObt1wBF+6rhSR7To4w70sbUxJowZIVRsDT2/Nd5jWKwYYP/mbMzfGoX8AxzmnD88f5F0z8IdBF9wcFUXu6atoahHaFZPXRUToO9h4HC2AnuoJK8406nkkoc=
